name: MoCoOld
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - cfitsio=3.470
  - charls=2.2.0
  - cloudpickle=2.0.0
  - cycler=0.11.0
  - dask-core=2022.2.1
  - dbus=1.13.18
  - decorator=5.1.1
  - entrypoints=0.4
  - expat=2.4.4
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - fsspec=2022.2.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - hdf5=1.10.6
  - icu=58.2
  - imageio=2.9.0
  - intel-openmp=2021.4.0
  - jpeg=9e
  - jupyter_client=7.3.1
  - jupyter_core=4.9.2
  - jxrlib=1.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libcurl=7.82.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - libzopfli=1.0.3
  - lz4-c=1.9.3
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mkl=2021.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - networkx=2.7.1
  - nibabel=3.2.2
  - numpy-base=1.21.5
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - parso=0.8.3
  - partd=1.2.0
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - prompt-toolkit=3.0.29
  - ptyprocess=0.7.0
  - pydicom=2.3.0
  - pygments=2.12.0
  - pyparsing=3.0.8
  - pyqt=5.9.2
  - python=3.10.4
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2021.3
  - qt=5.9.7
  - readline=8.1.2
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.38.3
  - tifffile=2021.7.2
  - tk=8.6.11
  - toolz=0.11.2
  - traitlets=5.2.0
  - tzdata=2022a
  - wcwidth=0.2.5
  - wheel=0.37.1
  - wurlitzer=3.0.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - bottleneck==1.3.4
    - certifi==2022.6.15
    - cytoolz==0.11.0
    - debugpy==1.5.1
    - h5py==3.6.0
    - imagecodecs==2021.8.26
    - ipykernel==6.13.0
    - ipython==7.33.0
    - jedi==0.18.1
    - jupyter-core==4.9.2
    - kiwisolver==1.3.1
    - locket==0.2.1
    - matplotlib==3.5.1
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - numexpr==2.7.3
    - numpy==1.21.5
    - pandas==1.4.2
    - patsy==0.5.2
    - pillow==9.0.1
    - pip==21.2.4
    - psutil==5.8.0
    - pywavelets==1.3.0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - scikit-image==0.19.2
    - scipy==1.7.3
    - setuptools==61.2.0
    - sip==4.19.13
    - spyder-kernels==2.3.0
    - statsmodels==0.13.2
    - tornado==6.1
